{% set name = "statsforecast" %}
{% set version = "2.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b5598e04dd868a243fcc8fcabec7cb14ac357a4976eb5848ff39dd19e8f49c4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -v
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - wheel
    - setuptools >=45
    - pybind11 >=2.10
  run:
    - python
    - cloudpickle
    - coreforecast >=0.0.17
    - numpy >=1.21.6
    - pandas <3.0.0
    - scipy >=1.7.3
    - statsmodels >=0.14.5
    - tqdm
    - fugue >=0.9.4
    - utilsforecast >=0.1.4
    - threadpoolctl >=3

test:
  imports:
    - statsforecast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Nixtla/statsforecast
  summary: Time series forecasting suite using statistical models
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    **StatsForecast** offers a collection of widely used univariate time series forecasting 
    models, including exponential smoothing and automatic `ARIMA` modeling optimized for 
    high performance using `numba`.

    - [Getting started](https://github.com/Nixtla/statsforecast/tree/main/#-getting-started-)
    - [Installation](https://github.com/Nixtla/statsforecast/tree/main/#-installation)

    PyPI: [https://pypi.org/project/statsforecast/](https://pypi.org/project/statsforecast/)

  doc_url: https://nixtla.github.io/statsforecast
  dev_url: https://github.com/Nixtla/statsforecast

extra:
  recipe-maintainers:
    - sugatoray
    - FedericoGarza
