{% set name = "statsforecast" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/statsforecast-{{ version }}.tar.gz
  sha256: 540db8fe3482930e053f6f5c9c2bb128100bfa1d838bcc3e7be7cd12c6f4f393

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numba
    - numpy
    - pandas
    - scipy
    - statsmodels

test:
  imports:
    - statsforecast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Nixtla/statsforecast/
  summary: Time series forecasting suite using statistical models
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    **StatsForecast** offers a collection of widely used univariate time series forecasting 
    models, including exponential smoothing and automatic `ARIMA` modeling optimized for 
    high performance using `numba`.

    - [Getting started](https://github.com/Nixtla/statsforecast/tree/main/#-getting-started-)
    - [Installation](https://github.com/Nixtla/statsforecast/tree/main/#-installation)

    PyPI: [https://pypi.org/project/statsforecast/](https://pypi.org/project/statsforecast/)

  doc_url: https://nixtla.github.io/statsforecast/
  dev_url: https://github.com/Nixtla/statsforecast/

extra:
  recipe-maintainers:
    - sugatoray
